### ISSUE TITLE
Print This Page Feature

### ISSUE THREAD

**Issue by mathteacher** [meeting-guide/react#22]
Hi All,

In proposing my booklet-generator project to @joshreisner, he mentioned integrating it in this react project as a print this page feature. I really like that idea and would like to make it happen as I think that would be a really useful feature for some users. I can't imagine utilizing LaTeX and [texlive.js](https://github.com/manuels/texlive.js/) like in the booklet-generator project would be necessary though and I'd like to avoid it since texlive.js is a really big dependency. I am wondering by what means the PDF of meetings (on the backend, settings page) in the 12-step-meeting-list WordPress plugin is created? Do you all know of any other lighter-weight means of producing PDFs with Javascript in the browser? I haven't started researching yet myself, but thought I'd see if you all have any ideas and also just formally submit that I'm working on this issue/feature.

Thanks,
Jacob

**Comment by joshreisner** [comment]
Hey @mathteacher the plugin uses [TCPDF](https://tcpdf.org/) which is not ideal, but does that to keep the footprint inside WordPress. I suggest we create this as a new service, separate from this project. We could locate it at print.meetingguide.org, for example, and pass it parameters like this:

https://print.meetingguide.org/?src=https://aasanjose.org/wp-admin/admin-ajax.php?action=meetings&day=any&region=mountain-view

I'll create a new repo for `print` and invite you. We can start by using my Linode VPS hosting but let's not be constrained by cost. If there's a service you know of that would make this easier I'll handle the funding.

**Comment by joshreisner** [comment]
Actually we could also locate this inside this repo, but have it be on the backend. I just don't want to add it as a dependency inside our `app.js` if that makes sense. The route could be:

https://react.meetingguide.org/print?src=https://aasanjose.org/wp-admin/admin-ajax.php?action=meetings&day=any&region=mountain-view

**Comment by joshreisner** [comment]
I think we want to be able to print from other vectors as well, like the WP plugin, so architecturally I think this should be located at print.meetingguide.org like in my original response. I'll start the repo and invite you.

**Comment by mathteacher** [comment]
That all sounds good. I do like the idea of keeping it separate so as you said other vectors could use the feature. It's pretty cool that a little ecosystem of tools are being built around the Meeting Guide JSON format.

I had imagined PDF creation all being in the frontend, but I think that's just because I run all my personal projects for free through GitHub Pages and thus am always avoiding doing any processing in the backend. I will do some research in regards to the best method to do PDF creation, but certainly since a server is available there are likely a lot more options.

**Comment by joshreisner** [comment]
Frontend or backend would be fine with me. Open to languages like Python and other frameworks like Node. Although not all this will be in the 1.0, I think it should be able to support:

    - [ ] Non-sequential page numbering for easy folding
    - [ ] Optional index at the end 
    - [ ] Be able to set starting page number
    - [ ] Different page sizing options
    - [ ] Be able to specify parameters like day, region, type, time, search, etc.
    - [ ] Nice widow-orphan flow control
    - [ ] Use of bold and more spacing
    - [ ] UTF-8 font with wheelchair symbol

**Comment by mathteacher** [comment]
I was imagining just a simple print this page button that would take the meetings currently displayed and create a PDF of those meetings that a user could print for personal use (which is simple enough I thought using LaTeX was probably overkill). You're definitely thinking bigger and I don't see why we couldn't have this project accomplish both my smaller goal and also your more customizable goal. With the features you're suggesting, using LaTeX again becomes an attractive tool as most (if not all) of those capabilities are baked into it. I will research and let you know what I come up with.
