### ISSUE TITLE
load-data.jsx checks for latitude twice

### ISSUE THREAD

**Issue by callipygiansoul** [meeting-guide/react#25]
I haven't gotten far enough into the code yet to submit PR's but I wanted to note a couple of things that _might_ be bugs, just so I don't forget.  This one is in load-data.jsx:

```
//build index of map pins
  if (meeting.latitude && meeting.latitude) {
```

Should probably be checking for longitude?

**Comment by joshreisner** [comment]
Thanks @callipygiansoul, good eye! We'd welcome a PR on this. Just FYI, please remember to build the assets for production `npm run prod` before submitting.
