### ISSUE TITLE
Index builders omit first slug

### ISSUE THREAD

**Issue by callipygiansoul** [meeting-guide/react#26]
Same disclaimer as in #25 about noting so I don't forget:

Several of the indexing blocks in load-data.jsx include something like this:

```
indexes.type[meeting.types[j]] = {
    key: Slugify(meeting.types[j]),
    name: meeting.types[j],
    slugs: [],
```

I'm wondering if that last line should be `slugs: [meeting.slug]` ?

**Comment by joshreisner** [comment]
I don't believe this is an issue, because it pushes it to the empty array right after.

```
indexes.region[meeting.region].slugs.push(meeting.slug);
```

However if you can reproduceably show it's not working and want to do a PR then 👌

**Comment by callipygiansoul** [comment]
Ah, no, that's totally right.  I'll close this issue.
